mymooc/apps/course/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2018/4/20 18:33
# @Author  : Wei
# @Email   : 592190443@qq.com
# @File    : urls.py
# @Software: PyCharm
from django.urls import path,re_path


from .views import CourseListView,CourseDetailView,CourseInfoView,CourseCommentView,AddCommentsView,CoursePlayView


app_name = "course"

urlpatterns = [
    path('list/',CourseListView.as_view(),name = 'course_list'),

    re_path('detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(),name = 'course_detail'),#从公开课跳转到课程详情

    re_path('info/(?P<course_id>\d+)/$', CourseInfoView.as_view(), name='course_info'),  # 从课程详情跳转到章节详情

    re_path('comment/(?P<course_id>\d+)/$', CourseCommentView.as_view(), name='course_comment'),  # 从章节详情跳转到课程评论

    path('addcomment/',AddCommentsView.as_view(),name = 'add_comment'), #提交评论的ajax请求

    re_path('play/(?P<vedio_id>\d+)/$', CoursePlayView.as_view(), name='course_play'),  # 从章节详情跳转视频播放

]

mymooc/apps/organization/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2018/4/19 11:11
# @Author  : Wei
# @Email   : 592190443@qq.com
# @File    : urls.py
# @Software: PyCharm
from django.urls import path,re_path


from .views import OrgView,UserAskView,OrgHomeView,OrgCourseView,OrgTeacherView,OrgDescView,AddFavView,TeacherListView,TeacherDetail


app_name = "organization"
urlpatterns = [

    # 课程组织结构
    path('list/', OrgView.as_view(),name='org_list'), #组织结构首页

    path('user_ask/',UserAskView.as_view(),name='user_ask'),  #用户咨询ajax请求处理

    re_path('^home/(?P<org_id>\d+)$', OrgHomeView.as_view(), name="org_home"),    #处理从机构列表页到机构主页的url

    re_path('^course/(?P<org_id>\d+)$', OrgCourseView.as_view(), name="org_course"), #机构主页到课程页

    re_path('teacher/(?P<org_id>\d+)$', OrgTeacherView.as_view(), name="org_teacher"), #机构主页到老师详情页

    re_path('^desc/(?P<org_id>\d+)$', OrgDescView.as_view(), name="org_desc"), #机构主页到机构详情页

    path('add_fav/',AddFavView.as_view(),name = "add_fav"),                 #处理点赞ajax请求

    #讲师
    path('teacher/list/', TeacherListView.as_view(), name="teacher_list"),  # 讲师列表页
    re_path('teacher/detail/(?P<teacher_id>\d+)$', TeacherDetail.as_view(), name="teacher_detail"),  # 讲师详情页



]

mymooc/apps/user/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2018/4/25 22:45
# @Author  : Wei
# @Email   : 592190443@qq.com
# @File    : urls.py
# @Software: PyCharm

from django.urls import path,re_path
from user.views import UserInfoView,UploadImageView,PwdUpdateView,SendEmailCodeView,UpdateEmail,MyCourseView,MyMsgView,MyFavOrgView,MyFavCourseView,MyFavTeacherView



app_name = "users"

urlpatterns = [
    #用户信息
    path('info/',UserInfoView.as_view(),name='users_info'),
    #用户头像上传
    path('image/upload/',UploadImageView.as_view(),name='image_upload'),

    #用户个人中心修改密码
    path('update/pwd/', PwdUpdateView.as_view(), name='update_pwd'),

    #修改发送邮箱验证码
    path('sendemail_code/', SendEmailCodeView.as_view(), name='sendemail_code'),

    #修改邮箱
    path('updata_email/', UpdateEmail.as_view(), name='update_email'),

    #我的课程
    path('mycourse/',MyCourseView.as_view(),name = 'mycourse'),
    #我的消息
    path('mymessage/',MyMsgView.as_view(),name = 'mymessage'),
    #我的收藏
        #机构
        path('myfav/org',MyFavOrgView.as_view(),name = 'myfav_org'),
        #课程
        path('myfav/course',MyFavCourseView.as_view(),name = 'myfav_course'),
        #讲师
        path('myfav/teacher',MyFavTeacherView.as_view(),name = 'myfav_teacher'),


]

mymooc/mymooc/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.views.static import serve  #处理静态图片

from mymooc.settings import MEDIA_ROOT ,STATIC_ROOT#寻找系统图片路径
from user.views import *
from organization.views import *
import xadmin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('xadmin/',xadmin.site.urls),

    #静态文件，自行配置，不使用django的自动管理
    re_path('static/(?P<path>.*)',serve,{'document_root':STATIC_ROOT}),

    # 处理图片显示的url, 使用Django自带serve, 传入参数告诉它去哪个路径找，我们有配置好的路径MEDIAROOT
    re_path('media/(?P<path>.*)', serve, {'document_root': MEDIA_ROOT}),

    path('index/',IndexView.as_view(),name="index"),
    path('login/',LoginView.as_view(),name="login"),
    path('logout/',LogoutView.as_view(),name="logout"),
    path('register/',ResgisterView.as_view(),name="register"),
    path('captcha/', include('captcha.urls')),  #验证码

    re_path('active/(?P<active_code>.*)/',ActiveUserView.as_view(),name='user_active') ,#用户激活

    re_path('reset/(?P<reset_code>.*)/',ResetView.as_view(),name = 'reset_pwd'), #忘记密码邮箱激活

    path('forget/',ForgetpwdView.as_view(),name='forget'),

    path('modify/',ModifyPwdView.as_view(),name='modify'),

    #课程机构url配置,分发
    path('org/', include('organization.urls' , namespace='org')),  #使用命名空间防止重名

    #课程列表页
    path('course/', include('course.urls', namespace='course')),  # 使用命名空间防止重名

    #用户个人中心相关地址
    path('users/', include('user.urls' , namespace='users')),  #使用命名空间防止重名



]
#全局404页面配置函数
handler404 = 'user.views.pag_not_found'
#全局500页面配置
handler500 = 'user.views.page_error'

mymooc/apps/course/models.py
# _*_ encoding:utf-8_*_
from django.db import models


from datetime import datetime
from organization.models import CourseOrg,Teacher

# Create your models here.


class Course(models.Model):
    DEGREE_CHOICES = (
        ("cj", "初级"),
        ("zj", "中级"),
        ("gj", "高级"),
    )

    name = models.CharField("课程名",max_length=50)
    desc = models.CharField("课程描述",max_length=300)
    detail = models.TextField("课程详情")
    degree = models.CharField('难度',choices=DEGREE_CHOICES, max_length=2)
    learn_times = models.IntegerField("学习时长(分钟数)",default=0)
    students = models.IntegerField("学习人数",default=0)
    fav_nums = models.IntegerField("收藏人数",default=0)
    image = models.ImageField("封面图",upload_to="courses/%Y/%m",max_length=100)
    is_banner = models.BooleanField('是否轮播', default=False)
    click_nums = models.IntegerField("点击数",default=0)
    add_time = models.DateTimeField("添加时间",default=datetime.now,)
    course_org = models.ForeignKey(CourseOrg,on_delete=models.CASCADE,verbose_name='所属机构',null=True,blank=True,default='')
    star = models.CharField('星级',max_length=2,default=5)
    category = models.CharField('课程类别',max_length=30,default='全栈开发')
    tag = models.CharField('课程标签',max_length=20,default='')
    teacher = models.ForeignKey(Teacher,null=True,blank=True,verbose_name="讲师",on_delete=models.CASCADE)
    need_know = models.CharField('课程须知',max_length=200,default='')
    learn_what = models.CharField('能学到什么',max_length=200,default='')

    class Meta:
        verbose_name = "课程"
        verbose_name_plural = verbose_name


        #获取课程的章节数
    def get_sum_lessons(self):
        return self.lesson_set.all().count()


        #获取这门课程的学习用户
    def get_learn_users(self):
        return self.usercourse_set.all()[:5]

    def __str__(self):
        return self.name


class BannerCourse(Course):
    class Meta:
        verbose_name = '课程轮播图'
        verbose_name_plural = verbose_name
        proxy = True  #不会生成表，具有表的功能，为了让一张表注册两个管理器


class Lesson(models.Model):
    course = models.ForeignKey(Course,verbose_name='课程',on_delete=models.CASCADE)
    name = models.CharField("章节名",max_length=100)
    add_time = models.DateTimeField("添加时间",default=datetime.now)

    class Meta:
        verbose_name = "章节"
        verbose_name_plural = verbose_name

    def __str__(self):
        return '《{0}》课程的章节 >> {1}'.format(self.course, self.name)

    def get_all_video(self):
        return self.video_set.all()



class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name="章节",on_delete=models.CASCADE)
    name = models.CharField("视频名",max_length=100)
    add_time = models.DateTimeField("添加时间", default=datetime.now)
    url = models.URLField('视频地址',max_length=200,default='')
    learn_times = models.IntegerField("学习时长(分钟数)", default=0)


    class Meta:
        verbose_name = "视频"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name="课程",on_delete=models.CASCADE)
    name = models.CharField("名称",max_length=100)
    download = models.FileField("资源文件",upload_to="course/resource/%Y/%m",max_length=100)
    add_time = models.DateTimeField("添加时间", default=datetime.now)

    class Meta:
        verbose_name = "课程资源"
        verbose_name_plural = verbose_name

mymooc/templates/html/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
     <p style="color: red;">链接失效</p>
</body>
</html>

mymooc/templates/html/course-comment.html
{% extends 'base.html' %}
{% load staticfiles %}
{% csrf_token %}
{% block title %}公开课评论{% endblock %}

{% block  add_css_js %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/muke/course/learn-less.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static '/css/muke/course/course-comment.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static '/css/muke/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/muke/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/muke/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/mooc.css' %}" />
{% endblock %}



<!--crumbs start-->
{% block bread_position %}
    <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
				<li><a href="{% url 'course:course_detail' course.id %}">课程详情</a>></li>
                <li>课程评论</li>
			</ul>
		</div>
	</div>
</section>
{% endblock %}


{% block content %}
    <div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>难度</strong></span>
                    <span class="meta">{{ course.degree }}</span>

                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value"><strong>时长</strong></span>
                    <span class="meta">{{ course.learn_times }}</span>
                    <em></em>
                </div>
                <div class="static-item">
                     <span class="meta-value"><strong>学习人数</strong></span>
                    <span class="meta">{{ course.students }}</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
            <div class="content-wrap clearfix">
                <div class="content">
                    <div class="mod-tab-menu">
                        <ul class="course-menu clearfix">
                            <li><a class="ui-tabs-active " id="learnOn"  href="{% url 'course:course_info' course.id %}"><span>章节</span></a></li>
                            <li><a id="commentOn" class="active" href="{% url 'course:course_comment' course.id %}"><span>评论</span></a></li>
                        </ul>
                    </div>

                    <!--发布评论-->
                    <div id="js-pub-container" class="issques clearfix js-form">
                        <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                            <textarea name="" id="js-pl-textarea" cols="30" rows="5" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！"></textarea>
                        </div>

                        <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">

                        <p class="global-errortip js-global-error"></p>
                    </div>



                    <div id="course_note">
                        <ul class="mod-post" id="comment-list">

                            {% for comment_obj in comments_objs  %}

                             <li class="post-row">
                                <div class="media">
                                    <span target="_blank"><img src='{{ MEDIA_URL }}{{ comment_obj.user.image }}' width='40' height='40' /></span>
                                </div>
                                <div class="bd">
                                    <div class="tit">
                                        <span target="_blank">{{ comment_obj.user.username }}</span>
                                    </div>
                                    <p class="cnt">{{ comment_obj.comments }}</p>
                                    <div class="footer clearfix">
                                        <span title="创建时间" class="l timeago">{{ comment_obj.add_time }}</span>
                                    </div>
                                </div>
                            </li>

                            {% endfor %}




                        </ul>
                    </div>

                </div>
                <div class="aside r">
                    <div class="bd">

                        <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                            {% for course_resource in all_course_resource %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ course_resource.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ course_resource.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>


                        <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacher.pic }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
        </span>
                            <span class="job">xxx</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.need_know }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.learn_what }}</dd>
                            </dl>
                        </div>
                    </div>




                        <div class="cp-other-learned  js-comp-tabs">
                            <div class="cp-header clearfix">
                                <h2 class="cp-tit l">该课的同学还学过</h2>
                            </div>
                            <div class="cp-body">
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                    <!-- img 200 x 112 -->
                                    <ul class="other-list">

                                        <li class="curr">
                                            <a href="/view/85?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/57035ff200014b8a06000338-240-135.jpg" alt="Java入门第一季">
                                                <span class="name autowrap">Java入门第一季</span>
                                            </a>
                                        </li>

                                        <li>
                                            <a href="/view/110?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/5703604a0001694406000338-240-135.jpg" alt="Java入门第三季">
                                                <span class="name autowrap">Java入门第三季</span>
                                            </a>
                                        </li>

                                        <li>
                                            <a href="/view/124?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/570360620001390f06000338-240-135.jpg" alt="Java入门第二季">
                                                <span class="name autowrap">Java入门第二季</span>
                                            </a>
                                        </li>

                                        <li>
                                            <a href="/view/47?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/570765d90001bf1406000338-240-135.jpg" alt="Spring MVC起步">
                                                <span class="name autowrap">Spring MVC起步</span>
                                            </a>
                                        </li>

                                        <li>
                                            <a href="/view/36?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/53e1d0470001ad1e06000338-240-135.jpg" alt="JavaScript入门篇">
                                                <span class="name autowrap">JavaScript入门篇</span>
                                            </a>
                                        </li>

                                    </ul>
                                </div>

                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                    <ul class="other-list">
                                        <li class="curr">
                                            <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                                <span class="name autowrap">Java工程师</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>

                            </div>
                        </div>

                    </div>    </div>
            </div>
            <div class="clear"></div>

        </div>

    </div>
</div>

{% endblock %}




{% block footer_js %}

    <script type="text/javascript">
    //添加评论

    $('#js-pl-submit').on('click', function(){
        var comments = $("#js-pl-textarea").val();
        if(comments == ""){
            alert("评论不能为空");
            return
        }

        $.ajax({
            cache: false,
            type: "POST",
            url:"{% url 'course:add_comment' %}",
            data:{'course_id':{{ course.id }}, 'comments':comments},
            async: true,
            beforeSend:function(xhr, settings){
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
             success: function(res) {
                dict = JSON.parse(res);
                if(ditc['status'] == 'fail'){
                    if(dict['msg'] == '用户未登录'){
                        window.location.href="{% url 'login' %}";
                    }else{
                        alert(dict['mag']);
                    }

                }
                else if(dict['status'] == 'success'){

                    alert("评论成功");
                    window.location.reload();
                }

            },
        });
    });


    </script>
{% endblock %}

mymooc/templates/html/course-video.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}章节信息{% endblock %}


{% block add_css_js %}

     <link rel="stylesheet" type="text/css" href="{% static '/css/muke/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static '/css/muke/common-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static '/css/muke/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static '/css/aui.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static '/css/mooc.css' %}" />
     <link rel="stylesheet" type="text/css" href="{% static '/css/muke/course/common-less.css' %}">


{% endblock %}


{% block bread_position %}
    <section>

        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'course:course_list' %}">公开课</a> > </li>
                <li><a href="{% url 'course:course_detail' course.id %}">课程详情</a> > </li>
                <li>章节信息</li>
            </ul>
        </div>

    </section>
{% endblock %}





{% block content %}


 <div id="main">

    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>难度</strong></span>
                    <span class="meta">{{ course.degree }}</span>

                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value"><strong>时长</strong></span>
                    <span class="meta">{{ course.learn_times }}</span>
                    <em></em>
                </div>
                <div class="static-item">
                     <span class="meta-value"><strong>学习人数</strong></span>
                    <span class="meta">{{ course.students }}</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>

    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"  href="{% url 'course:course_info' course.id %}"><span>章节</span></a></li>
                        <li><a id="commentOn" class="" href="{% url 'course:course_comment' course.id %}"><span>评论</span></a></li>
                    </ul>
                </div>
                <div id="notice" class="clearfix">
                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">Spring的文档以及相关的jar文件已上传</a> </div>
                </div>

                <div class="mod-chapters">

                    {% for lesson in lessons %}

                    <div class="chapter chapter-active" >
                        <h3>
                            <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                        </h3>

                        <ul class="video">
                            {% for vedio in lesson.get_all_video %}

                             <li>
                                <a target="_blank" href="{% url 'course:course_play' vedio.id %}" class="J-media-item studyvideo">
                                    {{ vedio.name }}
                                    <i class="study-state " style="width: 60px;margin-top: -20px">{{ vedio.learn_times }}分钟</i>
                                </a>
                            </li>

                            {% endfor %}

                        </ul>

                    </div>

                    {% endfor %}
                </div>

            </div>
            <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                            {% for course_resource in all_course_resource %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ course_resource.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ course_resource.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>


                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacher.pic }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
        </span>
                            <span class="job">xxx</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.need_know }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.learn_what }}</dd>
                            </dl>
                        </div>
                    </div>


                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">

                            {% for relate_course in relate_courses %}
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">

                                    <li class="curr">
                                        <a href="{% url 'course:course_detail' relate_course.id %}" target="_blank">
                                            <img src="{{ MEDIA_URL }}{{ relate_course.image }}" alt="{{ relate_course.name }}">
                                            <span class="name autowrap">{{ relate_course.name }}</span>
                                        </a>
                                    </li>

                                </ul>
                            </div>
                            {% endfor %}

                        </div>
                    </div>




                </div>    </div>



        </div>
        <div class="clear"></div>

    </div>

</div>

</div>

{% endblock %}

mymooc/templates/html/org-detail-teachers.html
{%  extends 'org_base.html' %}
{% load staticfiles %}
{% block title %}机构讲师{% endblock %}


{% block bread_postion %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'org:org_list' %}">课程机构</a>></li>
                <li>机构讲师</li>
            </ul>
        </div>
    </section>
{% endblock %}


{% block left_content %}
 <!-- teacher-->
    <div class="right companycenter layout" >
            <div class="head">
                <h1>机构教师</h1>
                <a class="green fr more" href="{% url 'org:teacher_list' %}">查看更多  >  </a>
            </div>
                    {% for teacher in all_teachers %}

                        <div class="diarys">
                            <div class="module5 share company-diary-box" style="padding:10px 0;">
                                 <div class="left">
                                    <img class="pic" src="{{ MEDIA_URL }}{{ teacher.pic }}"/>
                                     <p>昵称:{{ teacher.name }}</p>
                                 </div>
                                <div class="right">
                                    <div class="top">
                                        <div class="fl">
                                            <a href=""><h1>java开发教程</h1></a>
                                            <span>发表于：2015-10-12</span>
                                        </div>
                                    </div>
                                <div class="middle" style="border-bottom:0;">课程介绍</div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                    </div>

{% endblock %}

mymooc/templates/html/send_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <p>邮件已发送，请注意查收</p>
</body>
</html>

mymooc/templates/html/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% block title %}
课程收藏
{% endblock %}
<!--crumbs start-->
{% block crumbs %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:users_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}


{% block right-content %}
<div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                         <li ><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">

                        {% for course in course_list %}
                        <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
{% endblock %}